const path = require("path")
const {
  exportsDirectory,
  readMasterCv,
  writeGeneratedFile,
} = require("./lib")

const cv = readMasterCv()
const checkOnly = process.argv.includes("--check")
const generatedNotice =
  "<!-- Generated from content/cv/master.json. Do not edit this file directly. -->"

const bulletList = items => items.map(item => `- ${item}`).join("\n")

const renderRole = (role, highlightLimit) => {
  const highlights =
    typeof highlightLimit === "number"
      ? role.highlights.slice(0, highlightLimit)
      : role.highlights

  return [
    `### ${role.role} — ${role.company}`,
    `_${role.team} · ${role.location} · ${role.period}_`,
    "",
    role.summary,
    "",
    bulletList(highlights),
  ].join("\n")
}

const renderWorkItem = item =>
  [
    `### ${item.name}`,
    `_${item.context}_`,
    "",
    item.description,
    "",
    `Technologies and themes: ${item.tags.join(", ")}`,
    item.href ? `\nProject: ${item.href}` : "",
    item.sourceHref ? `Source: ${item.sourceHref}` : "",
  ]
    .filter(Boolean)
    .join("\n")

const fullCv = [
  generatedNotice,
  `# ${cv.profile.name}`,
  `_${cv.profile.title}_`,
  "",
  cv.profile.summary,
  "",
  cv.profile.contacts.map(contact => `[${contact.label}](${contact.href})`).join(" · "),
  "",
  `Last updated: ${cv.profile.updated}`,
  "",
  "## Professional experience",
  "",
  cv.professionalExperience.map(role => renderRole(role)).join("\n\n"),
  "",
  "## Engineering work",
  "",
  cv.engineeringWork
    .map(
      group =>
        `### ${group.title}\n\n${group.intro}\n\n${group.items
          .map(item => renderWorkItem(item).replace(/^### /, "#### "))
          .join("\n\n")}`
    )
    .join("\n\n"),
  "",
  "## Education",
  "",
  `### ${cv.education.qualification} — ${cv.education.institution}`,
  `_${cv.education.period}_`,
  "",
  bulletList(cv.education.details),
  "",
  cv.education.coursework
    .map(item => `- **${item.label}:** ${item.value}`)
    .join("\n"),
  "",
  "## University leadership",
  "",
  renderRole(
    {
      ...cv.universityLeadership,
      company: cv.universityLeadership.organisation,
      team: "SpaceX Hyperloop Pod Competition",
    },
    undefined
  ),
  "",
  "## Leadership and impact",
  "",
  cv.impact.map(item => `- **${item.title}:** ${item.detail}`).join("\n"),
  "",
  "## Professional development",
  "",
  cv.professionalDevelopment
    .map(group => `### ${group.title}\n\n${bulletList(group.items)}`)
    .join("\n\n"),
  "",
  "## Technical skills",
  "",
  cv.skills
    .map(skill => `- **${skill.category}:** ${skill.detail}`)
    .join("\n"),
].join("\n")

const briefRoles = cv.professionalExperience.filter(
  role => role.includeInBrief
)
const briefProjects = cv.engineeringWork.flatMap(group =>
  group.items.filter(item => item.includeInBrief)
)
const briefDevelopment = cv.professionalDevelopment.filter(
  group => group.includeInBrief
)
const briefSkills = cv.skills.filter(skill => skill.includeInBrief)

const briefCv = [
  generatedNotice,
  `# ${cv.profile.name}`,
  `_${cv.profile.title}_`,
  "",
  cv.profile.contacts.map(contact => `[${contact.label}](${contact.href})`).join(" · "),
  "",
  cv.profile.summary.split(". This is my long-form career record")[0] + ".",
  "",
  "## Experience",
  "",
  briefRoles.map(role => renderRole(role, 2)).join("\n\n"),
  "",
  "## Selected engineering work",
  "",
  briefProjects
    .map(item => `- **${item.name}:** ${item.description}`)
    .join("\n"),
  "",
  "## Education and leadership",
  "",
  `- **${cv.education.qualification}, ${cv.education.institution}** — ${cv.education.period}`,
  cv.universityLeadership.includeInBrief
    ? `- **${cv.universityLeadership.role}, ${cv.universityLeadership.organisation}:** ${cv.universityLeadership.summary}`
    : "",
  "",
  "## Professional development",
  "",
  briefDevelopment
    .map(group => `- **${group.title}:** ${group.items[0]}`)
    .join("\n"),
  "",
  "## Technical skills",
  "",
  briefSkills
    .map(skill => `- **${skill.category}:** ${skill.detail}`)
    .join("\n"),
].join("\n")

writeGeneratedFile(
  path.join(exportsDirectory, "full-cv.md"),
  fullCv,
  checkOnly
)
writeGeneratedFile(
  path.join(exportsDirectory, "brief-cv.md"),
  briefCv,
  checkOnly
)

console.log(
  checkOnly
    ? "Generated CV exports are current."
    : "Generated cv-exports/full-cv.md and cv-exports/brief-cv.md."
)
