import React from "react"
import { Link } from "gatsby"
import Layout from "../../components/Layout"
import Seo from "../../components/Seo"
import { profile } from "../../data/cv"

const evidence = [
  {
    id: "ingestion",
    eyebrow: "Workflow 01",
    title: "Preserve evidence before interpreting it",
    body: "Provider exports are retained as immutable raw evidence. Stable transaction identities let overlapping files converge without turning a repeated import into a duplicate financial event.",
    image: "/projects/budget-v2/activity.webp",
    alt: "Synthetic Budget V2 activity sheet showing fictional provider imports and their processing status",
    caption:
      "Synthetic demonstration generated by Budget V2: provider activity remains traceable while repeated files resolve idempotently.",
  },
  {
    id: "classification",
    eyebrow: "Workflow 02",
    title: "Automate only what can be decided safely",
    body: "Manual decisions outrank deterministic rules, which outrank provider categories. Ambiguous transactions remain visible for review instead of being silently forced into a spending category.",
    image: "/projects/budget-v2/review.webp",
    alt: "Synthetic Budget V2 review sheet containing a fictional unresolved transfer",
    caption:
      "Synthetic demonstration generated by Budget V2: unresolved meaning is presented as a review boundary, not guessed.",
  },
  {
    id: "reconciliation",
    eyebrow: "Workflow 03",
    title: "Reconcile transfers without guessing",
    body: "Both account legs remain real transactions. Automatic matching requires equal-and-opposite amounts, different accounts, a narrow date window and a unique reciprocal candidate; ties remain unmatched.",
    image: "/projects/budget-v2/transfers.webp",
    alt: "Synthetic Budget V2 transfer sheet showing a fictional matched card repayment",
    caption:
      "Synthetic demonstration generated by Budget V2: the paired legs reconcile to zero without deleting either source event.",
  },
  {
    id: "outputs",
    eyebrow: "Workflow 04",
    title: "Generate interfaces from the ledger",
    body: "The workbook is a generated read-only consumer of PostgreSQL data, not a second database. Operational checks travel with the export so visible results retain their reconciliation context.",
    image: "/projects/budget-v2/dashboard.webp",
    alt: "Synthetic Budget V2 dashboard showing a fictional zero-based plan and operational status",
    caption:
      "Synthetic demonstration generated by Budget V2: the workbook presents reviewed outputs from the canonical ledger.",
  },
]

const architecture = [
  "Provider files",
  "Immutable raw evidence",
  "Canonical PostgreSQL ledger",
  "Rules and manual review",
  "Workbook and aggregate insights",
]

const decisions = [
  "Integer minor units",
  "Stable source identities",
  "Explicit classification precedence",
  "Unique reciprocal transfer matching",
]

export default function BudgetV2Page() {
  const linkedIn = profile.contacts.find(
    contact => contact.label === "LinkedIn",
  )

  return (
    <Layout wide>
      <article className="budget-case-study">
        <header className="budget-case-study__hero">
          <p className="budget-case-study__eyebrow">
            Engineering case study · Synthetic demonstration
          </p>
          <h1>Building a trustworthy personal-finance data pipeline</h1>
          <p className="budget-case-study__disclosure">
            Entirely synthetic demonstration
          </p>
          <p>
            Budget V2 is a private, locally operated PostgreSQL ledger. This
            case study uses fictional accounts, descriptions, dates and amounts
            to demonstrate its engineering without exposing personal financial
            data.
          </p>
        </header>

        <section className="budget-case-study__intro">
          <div>
            <h2>Financial files are evidence, not a database</h2>
            <p>
              Overlapping exports, refunds, repayments and transfers can all
              distort a naïve spending total. Incomplete history also means a
              calculated account flow must not be presented as an authoritative
              balance.
            </p>
          </div>
          <div>
            <h2>Correctness before convenience</h2>
            <p>
              The system keeps exact integer money values, preserves provider
              evidence, separates technical transaction types from economic
              meaning and leaves uncertain cases open for explicit review.
            </p>
          </div>
        </section>

        <section aria-label="Architecture and engineering decisions">
          <ol
            className="budget-case-study__architecture"
            aria-label="Architecture flow"
          >
            {architecture.map(item => (
              <li key={item}>{item}</li>
            ))}
          </ol>
          <ul
            className="budget-case-study__decisions"
            aria-label="Engineering decisions"
          >
            {decisions.map(item => (
              <li key={item}>{item}</li>
            ))}
          </ul>
        </section>

        <section className="budget-case-study__evidence" aria-label="Workflow">
          {evidence.map(item => (
            <section className="budget-case-study__evidence-item" key={item.id}>
              <div>
                <p className="budget-case-study__label">{item.eyebrow}</p>
                <h2>{item.title}</h2>
                <p>{item.body}</p>
              </div>
              <figure>
                <img src={item.image} alt={item.alt} />
                <figcaption>{item.caption}</figcaption>
                <a
                  className="budget-case-study__evidence-link"
                  href={item.image}
                  aria-label={`Open full-size evidence: ${item.title}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  Open full-size evidence
                </a>
              </figure>
            </section>
          ))}
        </section>

        <section className="budget-case-study__limitations">
          <h2>What this does not claim</h2>
          <p>
            The public evidence is synthetic. Provider updates are file-based.
            Historical gaps are preserved rather than filled with invented
            balances or transfer pairs. Open Banking, authentication and a
            browser dashboard are outside this pilot.
          </p>
        </section>

        <section>
          <h2>What the architecture makes possible</h2>
          <p>
            Auditability comes from boundaries: raw evidence is immutable,
            interpretation is versioned, uncertainty remains visible and every
            interface is generated from the same canonical model.
          </p>
        </section>

        <section className="budget-case-study__downstream">
          <h2>Downstream outputs</h2>
          <p>
            The same canonical data supports comparable monthly analytics and
            review-gated email drafts. They are secondary consumers of
            deterministic facts, not alternate sources of financial truth.
          </p>
        </section>

        <section className="budget-case-study__closing">
          <h2>Reliable systems start with explicit boundaries.</h2>
          <div>
            <Link
              className="project-button project-button--primary"
              to="/experience/"
            >
              View experience
            </Link>{" "}
            <a
              className="project-button project-button--secondary"
              href={linkedIn.href}
              target="_blank"
              rel="noreferrer"
            >
              Connect on LinkedIn
            </a>
          </div>
        </section>
      </article>
    </Layout>
  )
}

export const Head = ({ location }) => (
  <Seo
    title="Budget V2 Engineering Case Study"
    description="A synthetic case study of immutable financial-data ingestion, deterministic classification and reconciliation in a PostgreSQL-first personal budgeting system."
    pathname={location.pathname}
  />
)
